### PR TITLE
Minor changes for readability + an extra test

### PR DESCRIPTION
**Pull request by xyproto**
Hi,
- Added a `ChangeFunc` type in an attempt to make it even clearer what the `func(*Mandelbrot)` type is used for.
- Also added a test.

Best regards,
Alexander F Rødseth

### CODE REVIEW

**Comment by xyproto** [comment]
No response, closing pull request.

**Comment by peterhellberg** [comment]
Sorry, didn't see this pull request since I don't have any notifications on my “toy projects”.

**Comment by xyproto** [comment]
Some projects are "toy projects", but welcome contributions. Some projects are "serious projects", but rejects or ignores contributions.

It's impossible to know which is which unless the project page has information about what type of project it is.

**Comment by peterhellberg** [comment]
Yes, I should have made that clear by adding a topic on the repo and a note in the README.

**Comment by xyproto** [comment]
No worries in any case! :)

**Pull request closed without merging**
